### ISSUE TITLE
Trying to update failed with "Download of dashd has failed, exiting"

### ISSUE THREAD

**Issue by lars-kolbowski** [kxcd/Masternode-Zeus#4]
When trying to update I kept getting"Download of dashd has failed, exiting". After Debugging it I figured out that the problem lies in the addKeyToStore function. Changing L491 from `return` to `return 0;` resolves this issue.
I'm not very familiar with bash scripting so, I'm not 100% sure my change still keeps the intended logic. But from my understanding of the code you check if the pastas key is already in the list, then if it's revoked it should give an error but if not you should return 0. `return` without specifying a value, implicitly returns the exit status of the last command executed in the function which returns the value of the `gpg -k $id|grep -q -i revoked`

**Comment by kxcd** [comment]
Yikes!  Thanks for reporting this bug, I will apply the fix.

**Comment by kxcd** [comment]
Yeah, what is happening here is the return is passing back the previous status from the grep which failed to match on 'revoked' so we know the key is valid, but in this sense a negative is a positive and the program bails when it shouldn't.  `return 0` is the fix.
